
package org.me.mgreply;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MGReplyWS", targetNamespace = "http://MGReply.me.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MGReplyWS {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMT", targetNamespace = "http://MGReply.me.org/", className = "org.me.mgreply.SendMT")
    @ResponseWrapper(localName = "sendMTResponse", targetNamespace = "http://MGReply.me.org/", className = "org.me.mgreply.SendMTResponse")
    @Action(input = "http://MGReply.me.org/MGReplyWS/sendMTRequest", output = "http://MGReply.me.org/MGReplyWS/sendMTResponse")
    public String sendMT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://MGReply.me.org/", className = "org.me.mgreply.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://MGReply.me.org/", className = "org.me.mgreply.SendMessageResponse")
    @Action(input = "http://MGReply.me.org/MGReplyWS/sendMessageRequest", output = "http://MGReply.me.org/MGReplyWS/sendMessageResponse")
    public String sendMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendNotification", targetNamespace = "http://MGReply.me.org/", className = "org.me.mgreply.SendNotification")
    @ResponseWrapper(localName = "sendNotificationResponse", targetNamespace = "http://MGReply.me.org/", className = "org.me.mgreply.SendNotificationResponse")
    @Action(input = "http://MGReply.me.org/MGReplyWS/sendNotificationRequest", output = "http://MGReply.me.org/MGReplyWS/sendNotificationResponse")
    public String sendNotification(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

}
