
package org.me.mgreplybulk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MGReplyBulkWSService", targetNamespace = "http://MGReplyBulk.me.org/", wsdlLocation = "classpath:wsdl/MGReplyBulkWS_1.wsdl")
public class MGReplyBulkWSService
    extends Service
{

    private final static URL MGREPLYBULKWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MGREPLYBULKWSSERVICE_EXCEPTION;
    private final static QName MGREPLYBULKWSSERVICE_QNAME = new QName("http://MGReplyBulk.me.org/", "MGReplyBulkWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Workspaces/TP/SmppClient/src/MGReplyBulkWS_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MGREPLYBULKWSSERVICE_WSDL_LOCATION = url;
        MGREPLYBULKWSSERVICE_EXCEPTION = e;
    }

    public MGReplyBulkWSService() {
        super(__getWsdlLocation(), MGREPLYBULKWSSERVICE_QNAME);
    }

    public MGReplyBulkWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MGREPLYBULKWSSERVICE_QNAME, features);
    }

    public MGReplyBulkWSService(URL wsdlLocation) {
        super(wsdlLocation, MGREPLYBULKWSSERVICE_QNAME);
    }

    public MGReplyBulkWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MGREPLYBULKWSSERVICE_QNAME, features);
    }

    public MGReplyBulkWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MGReplyBulkWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MGReplyBulkWS
     */
    @WebEndpoint(name = "MGReplyBulkWSPort")
    public MGReplyBulkWS getMGReplyBulkWSPort() {
        return super.getPort(new QName("http://MGReplyBulk.me.org/", "MGReplyBulkWSPort"), MGReplyBulkWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MGReplyBulkWS
     */
    @WebEndpoint(name = "MGReplyBulkWSPort")
    public MGReplyBulkWS getMGReplyBulkWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://MGReplyBulk.me.org/", "MGReplyBulkWSPort"), MGReplyBulkWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MGREPLYBULKWSSERVICE_EXCEPTION!= null) {
            throw MGREPLYBULKWSSERVICE_EXCEPTION;
        }
        return MGREPLYBULKWSSERVICE_WSDL_LOCATION;
    }

}
