
package org.me.mgreplybulk;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MGReplyBulkWS", targetNamespace = "http://MGReplyBulk.me.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MGReplyBulkWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMT", targetNamespace = "http://MGReplyBulk.me.org/", className = "org.me.mgreplybulk.SendMT")
    @ResponseWrapper(localName = "sendMTResponse", targetNamespace = "http://MGReplyBulk.me.org/", className = "org.me.mgreplybulk.SendMTResponse")
    @Action(input = "http://MGReplyBulk.me.org/MGReplyBulkWS/sendMTRequest", output = "http://MGReplyBulk.me.org/MGReplyBulkWS/sendMTResponse")
    public List<String> sendMT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<SendMTStruct> arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://MGReplyBulk.me.org/", className = "org.me.mgreplybulk.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://MGReplyBulk.me.org/", className = "org.me.mgreplybulk.SendMessageResponse")
    @Action(input = "http://MGReplyBulk.me.org/MGReplyBulkWS/sendMessageRequest", output = "http://MGReplyBulk.me.org/MGReplyBulkWS/sendMessageResponse")
    public List<String> sendMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<SendMessageStruct> arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendNotification", targetNamespace = "http://MGReplyBulk.me.org/", className = "org.me.mgreplybulk.SendNotification")
    @ResponseWrapper(localName = "sendNotificationResponse", targetNamespace = "http://MGReplyBulk.me.org/", className = "org.me.mgreplybulk.SendNotificationResponse")
    @Action(input = "http://MGReplyBulk.me.org/MGReplyBulkWS/sendNotificationRequest", output = "http://MGReplyBulk.me.org/MGReplyBulkWS/sendNotificationResponse")
    public List<String> sendNotification(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<SendNotificationStruct> arg2);

}
