
package pkg_cp_sip;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CP_SIP_WebService", targetNamespace = "http://PKG_CP_SIP/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CPSIPWebService {


    /**
     * 
     * @param username
     * @param serviceID
     * @param cpid
     * @param transactionData
     * @param password
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "Provisioning")
    @WebResult(targetNamespace = "http://PKG_CP_SIP/")
    @RequestWrapper(localName = "Provisioning", targetNamespace = "http://PKG_CP_SIP/", className = "pkg_cp_sip.Provisioning")
    @ResponseWrapper(localName = "ProvisioningResponse", targetNamespace = "http://PKG_CP_SIP/", className = "pkg_cp_sip.ProvisioningResponse")
    @Action(input = "http://PKG_CP_SIP/CP_SIP_WebService/ProvisioningRequest", output = "http://PKG_CP_SIP/CP_SIP_WebService/ProvisioningResponse")
    public List<String> provisioning(
        @WebParam(name = "Username", targetNamespace = "http://PKG_CP_SIP/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://PKG_CP_SIP/")
        String password,
        @WebParam(name = "Service_ID", targetNamespace = "http://PKG_CP_SIP/")
        String serviceID,
        @WebParam(name = "Transaction_Data", targetNamespace = "http://PKG_CP_SIP/")
        List<StringArray> transactionData,
        @WebParam(name = "CPID", targetNamespace = "http://PKG_CP_SIP/")
        String cpid);

}
