
package org.me.cgservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CGService", targetNamespace = "http://CGService.me.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CGService {


    /**
     * 
     * @param username
     * @param msisdn
     * @param serviceID
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserve", targetNamespace = "http://CGService.me.org/", className = "org.me.cgservice.Reserve")
    @ResponseWrapper(localName = "reserveResponse", targetNamespace = "http://CGService.me.org/", className = "org.me.cgservice.ReserveResponse")
    @Action(input = "http://CGService.me.org/CGService/reserveRequest", output = "http://CGService.me.org/CGService/reserveResponse")
    public String reserve(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "serviceID", targetNamespace = "")
        String serviceID,
        @WebParam(name = "MSISDN", targetNamespace = "")
        String msisdn);

    /**
     * 
     * @param username
     * @param transactionID
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commit", targetNamespace = "http://CGService.me.org/", className = "org.me.cgservice.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://CGService.me.org/", className = "org.me.cgservice.CommitResponse")
    @Action(input = "http://CGService.me.org/CGService/commitRequest", output = "http://CGService.me.org/CGService/commitResponse")
    public String commit(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID);

    /**
     * 
     * @param username
     * @param transactionID
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revoke", targetNamespace = "http://CGService.me.org/", className = "org.me.cgservice.Revoke")
    @ResponseWrapper(localName = "revokeResponse", targetNamespace = "http://CGService.me.org/", className = "org.me.cgservice.RevokeResponse")
    @Action(input = "http://CGService.me.org/CGService/revokeRequest", output = "http://CGService.me.org/CGService/revokeResponse")
    public String revoke(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID);

    /**
     * 
     * @param username
     * @param msisdn
     * @param serviceID
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "charge", targetNamespace = "http://CGService.me.org/", className = "org.me.cgservice.Charge")
    @ResponseWrapper(localName = "chargeResponse", targetNamespace = "http://CGService.me.org/", className = "org.me.cgservice.ChargeResponse")
    @Action(input = "http://CGService.me.org/CGService/chargeRequest", output = "http://CGService.me.org/CGService/chargeResponse")
    public String charge(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "serviceID", targetNamespace = "")
        String serviceID,
        @WebParam(name = "MSISDN", targetNamespace = "")
        String msisdn);

    /**
     * 
     * @param username
     * @param transactionID
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "refund", targetNamespace = "http://CGService.me.org/", className = "org.me.cgservice.Refund")
    @ResponseWrapper(localName = "refundResponse", targetNamespace = "http://CGService.me.org/", className = "org.me.cgservice.RefundResponse")
    @Action(input = "http://CGService.me.org/CGService/refundRequest", output = "http://CGService.me.org/CGService/refundResponse")
    public String refund(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID);

}
