
package org.me.mgpoolbulk;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MGPoolBulkWSService", targetNamespace = "http://MGPoolBulk.me.org/", wsdlLocation = "classpath:wsdl/MGPoolBulkWS_1.wsdl")
public class MGPoolBulkWSService
    extends Service
{

    private final static URL MGPOOLBULKWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MGPOOLBULKWSSERVICE_EXCEPTION;
    private final static QName MGPOOLBULKWSSERVICE_QNAME = new QName("http://MGPoolBulk.me.org/", "MGPoolBulkWSService");

    static {
        URL url = null;
        WebServiceException e = null;        
        
        try {
            url = MGPoolBulkWSService.class.getClassLoader().getResource("wsdl/MGPoolBulkWS_1.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        MGPOOLBULKWSSERVICE_WSDL_LOCATION = url;
        MGPOOLBULKWSSERVICE_EXCEPTION = e;
    }

    public MGPoolBulkWSService() {
        super(__getWsdlLocation(), MGPOOLBULKWSSERVICE_QNAME);
    }

    public MGPoolBulkWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MGPOOLBULKWSSERVICE_QNAME, features);
    }

    public MGPoolBulkWSService(URL wsdlLocation) {
        super(wsdlLocation, MGPOOLBULKWSSERVICE_QNAME);
    }

    public MGPoolBulkWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MGPOOLBULKWSSERVICE_QNAME, features);
    }

    public MGPoolBulkWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MGPoolBulkWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MGPoolBulkWS
     */
    @WebEndpoint(name = "MGPoolBulkWSPort")
    public MGPoolBulkWS getMGPoolBulkWSPort() {
        return super.getPort(new QName("http://MGPoolBulk.me.org/", "MGPoolBulkWSPort"), MGPoolBulkWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MGPoolBulkWS
     */
    @WebEndpoint(name = "MGPoolBulkWSPort")
    public MGPoolBulkWS getMGPoolBulkWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://MGPoolBulk.me.org/", "MGPoolBulkWSPort"), MGPoolBulkWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MGPOOLBULKWSSERVICE_EXCEPTION!= null) {
            throw MGPOOLBULKWSSERVICE_EXCEPTION;
        }
        return MGPOOLBULKWSSERVICE_WSDL_LOCATION;
    }

}
