
package pkg_directroute;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DirectRoute", targetNamespace = "http://PKG_DirectRoute/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DirectRoute {


    /**
     * 
     * @param username
     * @param xms
     * @param msisdn
     * @param serviceID
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "generate_Service_Request")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generate_Service_Request", targetNamespace = "http://PKG_DirectRoute/", className = "pkg_directroute.GenerateServiceRequest")
    @ResponseWrapper(localName = "generate_Service_RequestResponse", targetNamespace = "http://PKG_DirectRoute/", className = "pkg_directroute.GenerateServiceRequestResponse")
    @Action(input = "http://PKG_DirectRoute/DirectRoute/generate_Service_RequestRequest", output = "http://PKG_DirectRoute/DirectRoute/generate_Service_RequestResponse")
    public String generateServiceRequest(
        @WebParam(name = "Username", targetNamespace = "")
        String username,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "ServiceID", targetNamespace = "")
        String serviceID,
        @WebParam(name = "MSISDN", targetNamespace = "")
        String msisdn,
        @WebParam(name = "XMS", targetNamespace = "")
        String xms);

}
